Fix TS2339 error: Property 'name' does not exist on type 'User'
\
The type `User` did not have a `name` property, causing a TypeScript error. Added `name` property to the `User` interface.